// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: tutorial.proto

package content

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TutorialServiceClient is the client API for TutorialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TutorialServiceClient interface {
	CreateTutorial(ctx context.Context, in *Tutorial, opts ...grpc.CallOption) (*ReqID, error)
	UpdateTutorial(ctx context.Context, in *Tutorial, opts ...grpc.CallOption) (*ReqID, error)
	DeleteTutorial(ctx context.Context, in *ReqID, opts ...grpc.CallOption) (*ReqID, error)
	GetTutorial(ctx context.Context, in *ReqID, opts ...grpc.CallOption) (*Tutorial, error)
}

type tutorialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTutorialServiceClient(cc grpc.ClientConnInterface) TutorialServiceClient {
	return &tutorialServiceClient{cc}
}

func (c *tutorialServiceClient) CreateTutorial(ctx context.Context, in *Tutorial, opts ...grpc.CallOption) (*ReqID, error) {
	out := new(ReqID)
	err := c.cc.Invoke(ctx, "/TutorialService/CreateTutorial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorialServiceClient) UpdateTutorial(ctx context.Context, in *Tutorial, opts ...grpc.CallOption) (*ReqID, error) {
	out := new(ReqID)
	err := c.cc.Invoke(ctx, "/TutorialService/UpdateTutorial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorialServiceClient) DeleteTutorial(ctx context.Context, in *ReqID, opts ...grpc.CallOption) (*ReqID, error) {
	out := new(ReqID)
	err := c.cc.Invoke(ctx, "/TutorialService/DeleteTutorial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorialServiceClient) GetTutorial(ctx context.Context, in *ReqID, opts ...grpc.CallOption) (*Tutorial, error) {
	out := new(Tutorial)
	err := c.cc.Invoke(ctx, "/TutorialService/GetTutorial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TutorialServiceServer is the server API for TutorialService service.
// All implementations must embed UnimplementedTutorialServiceServer
// for forward compatibility
type TutorialServiceServer interface {
	CreateTutorial(context.Context, *Tutorial) (*ReqID, error)
	UpdateTutorial(context.Context, *Tutorial) (*ReqID, error)
	DeleteTutorial(context.Context, *ReqID) (*ReqID, error)
	GetTutorial(context.Context, *ReqID) (*Tutorial, error)
	mustEmbedUnimplementedTutorialServiceServer()
}

// UnimplementedTutorialServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTutorialServiceServer struct {
}

func (UnimplementedTutorialServiceServer) CreateTutorial(context.Context, *Tutorial) (*ReqID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTutorial not implemented")
}
func (UnimplementedTutorialServiceServer) UpdateTutorial(context.Context, *Tutorial) (*ReqID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTutorial not implemented")
}
func (UnimplementedTutorialServiceServer) DeleteTutorial(context.Context, *ReqID) (*ReqID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTutorial not implemented")
}
func (UnimplementedTutorialServiceServer) GetTutorial(context.Context, *ReqID) (*Tutorial, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTutorial not implemented")
}
func (UnimplementedTutorialServiceServer) mustEmbedUnimplementedTutorialServiceServer() {}

// UnsafeTutorialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TutorialServiceServer will
// result in compilation errors.
type UnsafeTutorialServiceServer interface {
	mustEmbedUnimplementedTutorialServiceServer()
}

func RegisterTutorialServiceServer(s grpc.ServiceRegistrar, srv TutorialServiceServer) {
	s.RegisterService(&TutorialService_ServiceDesc, srv)
}

func _TutorialService_CreateTutorial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tutorial)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorialServiceServer).CreateTutorial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TutorialService/CreateTutorial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorialServiceServer).CreateTutorial(ctx, req.(*Tutorial))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorialService_UpdateTutorial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tutorial)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorialServiceServer).UpdateTutorial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TutorialService/UpdateTutorial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorialServiceServer).UpdateTutorial(ctx, req.(*Tutorial))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorialService_DeleteTutorial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorialServiceServer).DeleteTutorial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TutorialService/DeleteTutorial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorialServiceServer).DeleteTutorial(ctx, req.(*ReqID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorialService_GetTutorial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorialServiceServer).GetTutorial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TutorialService/GetTutorial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorialServiceServer).GetTutorial(ctx, req.(*ReqID))
	}
	return interceptor(ctx, in, info, handler)
}

// TutorialService_ServiceDesc is the grpc.ServiceDesc for TutorialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TutorialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TutorialService",
	HandlerType: (*TutorialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTutorial",
			Handler:    _TutorialService_CreateTutorial_Handler,
		},
		{
			MethodName: "UpdateTutorial",
			Handler:    _TutorialService_UpdateTutorial_Handler,
		},
		{
			MethodName: "DeleteTutorial",
			Handler:    _TutorialService_DeleteTutorial_Handler,
		},
		{
			MethodName: "GetTutorial",
			Handler:    _TutorialService_GetTutorial_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tutorial.proto",
}
